cortex-lab/alyx

- alyx/subjects/admin.py
- alyx/subjects/models.py
with some guesses about syntax
closes #30
> add the formula

- alyx/Makefile
- alyx/actions/admin.py
- alyx/actions/models.py
- alyx/alyx/base.py
- alyx/subjects/admin.py
- alyx/subjects/models.py
- alyx/subjects/views.py
* Closes #39
* Closes #41
* Closes #42 
* Closes #43 
* Closes #45
* Closes #46
* Closes #47
* Closes #48 
* Closes #52
* Closes #54
* Closes #55 
* Closes #56 
* Closes #57 
* Closes #58 
* Closes #61
> [WIP] Minor improvements

- alyx/alyx/urls.py
- alyx/subjects/models.py
- alyx/subjects/serializers.py
Fixes /subject endpoint. Now allows `[-._~\w]` characters. ie dash dot underscore tilde alphanumerics for nickname. Enforces this on the model.
Added water restriction fields to detail endpoint.
Ready to merge @rossant 
Closes #136 #101 #188
> Add water restriction fields to /subjects/[nickname] endpoint.

- alyx/alyx/urls.py
- alyx/misc/views.py
- alyx/subjects/serializers.py
- alyx/subjects/views.py
> Added water restriction endpoint and SubjectList filter

- .travis.yml
- requirements.txt
> Update to django 1.11

- alyx/alyx/base.py
- alyx/alyx/settings.py
- alyx/subjects/admin.py
- requirements.txt
> Add django-reversion support

- alyx/actions/tests_rest.py
- alyx/subjects/serializers.py
- alyx/subjects/tests_rest.py
> added some tests and suggestions for tests

- alyx/actions/admin.py
- alyx/actions/urls.py
- alyx/actions/views.py
- alyx/actions/water.py
- alyx/subjects/admin.py
- alyx/subjects/views.py
- alyx/templates/water_history.html
> Add water history custom view

- alyx/subjects/zygosities.py
@rossant added a new zygosity rule. Question: How will the new rule get propagated to existing mice?
> add zygosities rule for RCLcg

- alyx/subjects/models.py
Here is the full set of possible cases that can be inputs to "_zygosity_from_parents", along with the correct answers. I tested the function in this commit and it produces all of these answers. Maybe we can make a unit test out of this, I guess? 
```
('+/+', '+/+') '+/+'
('+/+', '+/-') '+'
('+/+', '-/-') '+/-'
('+/+', '+') '+'
('+/+', None) '+/-'
('+/-', '+/+') '+'
('+/-', '+/-') None
('+/-', '-/-') None
('+/-', '+') None
('+/-', None) None
('-/-', '+/+') '+/-'
('-/-', '+/-') None
('-/-', '-/-') '-/-'
('-/-', '+') None
('-/-', None) '-/-'
('+', '+/+') '+'
('+', '+/-') None
('+', '-/-') None
('+', '+') None
('+', None) None
(None, '+/+') '+/-'
(None, '+/-') None
(None, '-/-') '-/-'
(None, '+') None
(None, None) '-/-'
```
> updated formula for zyg from parent

- alyx/subjects/zygosities.py
> update the RCLcg.Vg zygosities rule

- alyx/actions/tests_rest.py
- alyx/actions/views.py
- alyx/alyx/urls.py
- alyx/data/admin.py
- alyx/data/management/commands/globus.py
- alyx/data/models.py
- alyx/data/serializers.py
- alyx/data/tests_rest.py
- alyx/data/transfers.py
- alyx/data/views.py
- alyx/misc/management/commands/report.py
- alyx/misc/views.py
* Return implant-weight in water requirement endpoint
* Rename path to globus_path in DataRepository
* Add timezone field to DataRepository
* Normalize FileRecord relative_paths: they must now be of the form nickname/YYYY-MM-DD/n/...
* Slightly clearer water restriction daily email
* The /register-file is still a work in progress
> Merge dev to master

- alyx/data/management/commands/files.py
- alyx/data/transfers.py
Added commands:
manage.py files bulksync
manage.py files bulktransfer
Ignore inactive repositories and minimize Transfer requests to the Globus SDK
> Globus bulk transfers

- alyx/subjects/serializers.py
remove sessions-details
add weighing information
> REST: subjects-details serializer

- alyx/actions/admin.py
- alyx/data/models.py
- alyx/data/serializers.py
- alyx/data/tests_rest.py
- alyx/data/transfers.py
- alyx/data/views.py
- alyx/misc/admin.py
- alyx/misc/models.py
- alyx/misc/serializers.py
- alyx/subjects/admin.py
- alyx/subjects/models.py
- alyx/subjects/serializers.py
Repositories moved to lab instead of projects.
Download REST endpoint accepts multiple files.
> Projects ephys dbchanges

- alyx/actions/models.py
- alyx/actions/views.py
> Schema changes

- .travis.yml
- alyx/actions/admin.py
- alyx/actions/fixtures/actions.proceduretype.json
- alyx/data/admin.py
- alyx/data/fixtures/data.datasettype.json
- alyx/data/tests_rest.py
- alyx/data/transfers.py
- alyx/data/views.py
- alyx/subjects/admin.py
- bugfix actions.admin for Val
- bugfix transfers on first private repository (angelaki)
- init fixtures for data.dataset_types and actions.protocols
> Release 17-DEC-2019

- setup.py
Hello! Had trouble running the setup script -- using the `sudo -u postgres` syntax leaves the home directory set for the calling user, and even when the postgres group was given write and execution privileges I was still getting permissions errors. Didn't want to have to make the postgres user the owner of the repository directory, so changed the `_psql` command to use `sudo su - postgres -c "command"` syntax. This runs the command as the postgres user in a login shell which fixed permissions errors for me. I don't think this has any negative effects, but could be wrong.
I also was getting errors calling `alyxvenv/bin/python` because I accidentally named mine `alyxenv`, so to make it a bit more flexible (not have to have an exactly correctly named venv) I added a check that the user was …
> Permissions issues using sudo -u postgres & other minor setup tweaks

- alyx/actions/serializers.py
- alyx/actions/tests_rest.py
- alyx/actions/views.py
- alyx/alyx/urls.py
New REST endpoint for surgeries
> Surgeries rest

- scripts/deployment_examples/docker/Dockerfile
- scripts/deployment_examples/docker/README
- scripts/deployment_examples/docker/alyx-entrypoint.sh
- scripts/deployment_examples/docker/docker-compose.yml
- scripts/deployment_examples/docker/dot-env.example
Hello - per discussions in IBL with @oliche, 
submitting the docker/docker compose setup for Alyx we've used for some initial testing.
Seems to work to test pre-existing dumps (see README), the entrypoint.sh would need to be adjusted/adapted 
in the case of a clean room install / or for auto retrieval of dumpfiles.
Feedback / adjustments welcome :) 
Thanks,
- Chris
> example docker/docker-compose setup

- .github/workflows/main.yml
- README.md
- alyx/alyx/settings.py
Coverage and Github actions CI work on this branch, I need to adapt 2 tiny things to make it work on master but wanted to get a review first
> GitHub actions

- alyx/templates/tasks.html
add incomplete status to tasks page
> update tasks page to show incomplete tasks

- README.md
- alyx/alyx/settings_template.py
Update to ensure the permissions on the log files are read/write, apache user is created before attempting to grant permissions to it, and utilizing the rotating log functionality.
> Logging fix

- .github/workflows/main.yml
Matching postgres version to what is being hosted on rds
> specifying postgres v13 for CI

- alyx/alyx/base.py
- alyx/misc/tests_rest.py
- alyx/misc/urls.py
- alyx/misc/views.py
Support for querying multiple caches
> Cache tags

- alyx/data/fixtures/data.datasettype.json
fixes for widefiled filename patterns
> Auto stash before checking out "origin/dev"

- alyx/actions/management/commands/check_water_admin.py
- alyx/actions/models.py
- alyx/actions/notifications.py
- alyx/actions/tests.py
Creates a notification if a water restricted subject hasn't been weighed on a given day.
> Notification for missing weighing record

- .github/workflows/main.yml
- alyx/actions/tests_rest.py
- alyx/actions/views.py
- alyx/misc/serializers.py
- requirements.txt
> The sessions endpoint dataset filters doesn't return non-existent #670
